Рефакторинг бека
PhonikTop/clocks pull request #1
Opened 2024-09-04 12:45 UTC by PhonikTop

2024-09-04 15:58 UTC, Str1kez commented on clocks/Dockerfile
> +COPY . .
Наверное на этом слое не нужен весь код, можно скопировать его в соответствующих

2024-09-04 16:03 UTC, Str1kez commented on clocks/meetings/migrations/0001_initial.py
все миграции можно в одну

2024-09-04 16:05 UTC, Str1kez commented on clocks/meetings/models.py
> +    room_id = models.ForeignKey(
```suggestion
    room = models.ForeignKey(
```
это же уже по сути объект

2024-09-04 16:10 UTC, Str1kez commented on clocks/meetings/serializers.py
> +                self.fields.pop(field_name)
`self.fields` вроде list и так не удалишь

2024-09-04 16:15 UTC, Str1kez commented on clocks/meetings/serializers.py
> +    active = serializers.BooleanField()
разве это автоматом не делается `ModelSerializer`? Вроде для этого он и нужен

2024-09-04 16:17 UTC, Str1kez commented on clocks/meetings/views.py
> +        if serializer.is_valid():
лучше наоборот not is_valid проверить и сразу вернуть ошибку, будет меньше вложенности для последующего кода

2024-09-04 16:17 UTC, Str1kez commented on clocks/meetings/views.py
> +        if serializer.is_valid():
следующее условие аналогично

2024-09-04 16:21 UTC, Str1kez commented on clocks/meetings/views.py
> +                                       fields=["id", "room_id", "task_name", "votes", "average_score", "active"])
```suggestion
        serializer = MeetingSerializer(meeting)
```

2024-09-04 16:26 UTC, Str1kez commented on clocks/api/api_utils.py
> +        self.error_response = partial(self.return_api_response, type_message="error")
можно тут прокинуть сразу статус 400 и не передавать его в коде

2024-09-04 16:37 UTC, Str1kez commented on clocks/meetings/views.py
> +class GetMeetingView(APIView):
Можно использовать [RetrieveApiView](https://www.django-rest-framework.org/api-guide/generic-views/#retrieveapiview)

2024-09-04 16:43 UTC, Str1kez commented on clocks/meetings/views.py
> +        meeting = get_object_or_404(Meeting, id=meeting_id)
можно брать комнату и делать select_related митинга, так один запрос будет только

2024-09-04 16:47 UTC, Str1kez commented on clocks/meetings/views.py
> +        meeting.save()
Можно в модели сделать метод `reset_to_default` и вызвать его тут

2024-09-04 16:49 UTC, Str1kez commented on clocks/meetings/views.py
> +        meeting = get_object_or_404(Meeting, id=meeting_id)
аналогично с select_related

2024-09-04 16:49 UTC, Str1kez commented on clocks/meetings/views.py
> +        if serializer.is_valid():
проверять not is_valid

2024-09-04 17:26 UTC, PhonikTop commented on clocks/api/api_utils.py
> +        self.error_response = partial(self.return_api_response, type_message="error")
> можно тут прокинуть сразу статус 400 и не передавать его в коде

А если нужно выводить другой статус ошибки?

2024-09-04 18:36 UTC, Str1kez commented on clocks/api/api_utils.py
> +        self.error_response = partial(self.return_api_response, type_message="error")
тогда будешь передавать его где надо, а по дефолту будет 400

2024-09-04 18:38 UTC, Str1kez commented on clocks/requirements.txt
> +Django~=5.1
лучше явно указывай полностью версию

2024-09-04 18:39 UTC, Str1kez commented on clocks/requirements.txt
> +redis~=5.1.0b7
не надо бета релизы юзать)

2024-09-04 18:40 UTC, Str1kez commented on clocks/rooms/serializers.py
> +from .models import Room
лучше использовать везде абсолютные пути импорта

2024-09-04 18:42 UTC, Str1kez commented on clocks/requirements.txt
> +Django~=5.1
и версию с ==

2024-09-04 18:47 UTC, Str1kez commented on clocks/rooms/views.py
> +class RoomCreateView(APIView):
CreateAPIView, можно больше использовать дженериков -> меньше кода

2024-09-04 19:14 UTC, Str1kez commented on clocks/ws/consumers.py
почему решил не делать async консюмера?

2024-09-04 19:16 UTC, Str1kez commented on clocks/requirements.txt
> +daphne
наверное можно дропнуть daphne

2024-09-04 19:26 UTC, Str1kez commented on clocks/rooms/models.py
> +    current_meeting = models.OneToOneField(
Вроде и не нужно, по сути один митинг может быть активен для комнаты

2024-09-04 20:24 UTC, PhonikTop commented on clocks/meetings/serializers.py
> +                self.fields.pop(field_name)
Я просто подумал, что так сериализатор всегда будет работать со всеми полями, определенными по умолчанию, игнорируя те параметры, что в него передают в других модулях проекта.

2024-09-04 20:36 UTC, PhonikTop commented on clocks/rooms/models.py
> +    current_meeting = models.OneToOneField(
> Вроде и не нужно, по сути один митинг может быть активен для комнаты

В каком смысле?

2024-09-04 20:37 UTC, PhonikTop commented on clocks/requirements.txt
> +daphne
> наверное можно дропнуть daphne

На нем же web socket держится

2024-09-04 20:43 UTC, PhonikTop commented on clocks/ws/consumers.py
> почему решил не делать async консюмера?

Я начал, но у меня из-за этого была ошибка связанная с ретурном данных о голосах. Я возился с ней больше дня, но ничего не помогало. Решил просто не делать это, оставил код синхронным, но рабочим.

2024-09-04 20:46 UTC, PhonikTop commented on clocks/rooms/serializers.py
> +from .models import Room
> лучше использовать везде абсолютные пути импорта

У меня при запуске через runserver выходила ошибка 
```from ..meetings.models import Meeting
ImportError: attempted relative import beyond top-level package```

2024-09-05 07:36 UTC, Str1kez commented on clocks/meetings/serializers.py
> +                self.fields.pop(field_name)
да решение нормальное, сам метод pop у листа на индекс работает же

2024-09-05 07:38 UTC, Str1kez commented on clocks/rooms/serializers.py
> +from .models import Room
Это же опять относительные. Попробуй `clocks.meetings.models import Meeting`

2024-09-05 07:39 UTC, Str1kez commented on clocks/ws/consumers.py
а в чем именно ошибка была? Запросы к бд обернул в `sync_to_async`?

2024-09-05 07:40 UTC, Str1kez commented on clocks/requirements.txt
> +daphne
не может быть такого. У тебя же uvicorn есть

2024-09-05 07:43 UTC, Str1kez commented on clocks/rooms/models.py
> +    current_meeting = models.OneToOneField(
Непонятно зачем нужен current_meeting, ведь текущий митинг можно найти `Room.objects.filter(meetings__is_active=True)`

2024-09-05 07:46 UTC, Str1kez commented on clocks/meetings/serializers.py
> +                self.fields.pop(field_name)
и как будто можно было проще сделать без цикла 
```python
self.fields = list(existing - allowed)
```

2024-09-05 09:28 UTC, PhonikTop commented on clocks/ws/consumers.py
> а в чем именно ошибка была? Запросы к бд обернул в `sync_to_async`?

Да. Ошибка была в том, что объект корутины не может возвращаться. Я подумал, что это из-за вывода в самом декораторе, решил, что пока не смогу с этим справиться.

2024-09-05 09:33 UTC, PhonikTop commented on clocks/rooms/models.py
> +    current_meeting = models.OneToOneField(
Подумал, что так будет читабельнее. Плюс, на момент, когда писал это, не догадывался о существовании фильтра.

2024-09-08 11:13 UTC, Str1kez commented on Dockerfile
> +RUN python manage.py collectstatic --noinput
не надо ничего мигрировать на этапе сборки образа

2024-09-08 11:43 UTC, Str1kez commented on Dockerfile
> +    daphne -b 0.0.0.0 -p 8001 settings.asgi:application & \
для чего нужен?

2024-09-08 11:45 UTC, Str1kez commented on nginx/default.conf
> +    }
можно вместе в daphne дропнуть как будто

2024-09-08 11:51 UTC, Str1kez commented on clocks/meetings/views.py
> +        room = get_object_or_404(Room, id=room_id)
сериализатор уже достал объект, нет?

2024-09-08 11:55 UTC, Str1kez commented on clocks/meetings/views.py
> +        }, status=status.HTTP_201_CREATED)
лишнее

2024-09-08 11:56 UTC, Str1kez commented on clocks/meetings/views.py
> +        return response.success_response(msg="Meeting info", data=serializer.data, response_status=status.HTTP_200_OK)
Разве это не логика работы RetrieveAPIView?

2024-09-08 12:05 UTC, Str1kez commented on clocks/meetings/views.py
> +    lookup_field = "id"
лишнее

2024-09-08 12:12 UTC, Str1kez commented on clocks/rooms/views.py
> +                                       response_status=status.HTTP_400_BAD_REQUEST)
тоже лишнее, можно все данные отдавать при создании

2024-09-08 12:13 UTC, Str1kez commented on clocks/rooms/views.py
> +        return Room.objects.all()
`queryset = `

2024-09-08 12:16 UTC, Str1kez commented on clocks/rooms/views.py
> +class RoomDetailView(RetrieveAPIView, DestroyAPIView):
```suggestion
class RoomDetailView(RetrieveDestroyAPIView):
```

2024-09-08 12:17 UTC, Str1kez commented on clocks/rooms/views.py
> +                                         response_status=status.HTTP_204_NO_CONTENT)
```suggestion
```

2024-09-08 12:17 UTC, Str1kez commented on clocks/rooms/views.py
> +        return Room.objects.get(id=self.kwargs.get("id"))
`queryset=`

2024-09-08 12:18 UTC, Str1kez commented on clocks/rooms/views.py
> +                "role": "observer" if role == "observer" else "voter",
роли в Enum лучше

2024-09-08 12:20 UTC, Str1kez commented on clocks/rooms/views.py
> +                "role": "observer" if role == "observer" else "voter",
и зачем это все, если можно просто передавать `room.users`?

2024-09-08 12:23 UTC, Str1kez commented on clocks/rooms/views.py
> +                "role": "observer" if role == "observer" else "voter",
вообще лучше выпилить это и добавить что-то такое
```python
    def get_serializer(self, *args, **kwargs):
        kwargs['fields'] = ['users']
        return super().get_serializer(*args, **kwargs)
```

2024-09-08 12:25 UTC, Str1kez commented on clocks/rooms/views.py
> +        return Meeting.objects.filter(room=room, active=False)
`queryset = `

2024-09-08 12:27 UTC, Str1kez commented on clocks/settings/asgi.py
> +from ws.rounting import ws_urlpatterns
```suggestion
from ws.routing import ws_urlpatterns
```

2024-09-08 12:28 UTC, Str1kez commented on requirements.txt
> +Django~=5.1.1
```suggestion
Django==5.1.1
```

2024-09-09 05:19 UTC, PhonikTop commented on Dockerfile
> +    daphne -b 0.0.0.0 -p 8001 settings.asgi:application & \
Что именно? Daphne? Nginx?

2024-09-09 22:15 UTC, PhonikTop commented on clocks/meetings/views.py
> +        room = get_object_or_404(Room, id=room_id)
> сериализатор уже достал объект, нет?

Почему? это же уже другая модель. Я думал, он так не может

2024-09-09 22:23 UTC, PhonikTop commented on clocks/meetings/views.py
> +    lookup_field = "id"
А как он будет получать эти переменные? У GenericAPIView lookup_field = 'pk', а queryset serializer_class оба None

2024-09-09 22:33 UTC, PhonikTop commented on clocks/rooms/views.py
> +        return Room.objects.get(id=self.kwargs.get("id"))
Она же тут должна получать айди комнаты.

2024-09-17 08:37 UTC, Str1kez commented on Dockerfile
> +    daphne -b 0.0.0.0 -p 8001 settings.asgi:application & \
daphne

2024-09-17 08:40 UTC, Str1kez commented on clocks/meetings/views.py
> +        room = get_object_or_404(Room, id=room_id)
а, да, ты прав

2024-09-17 08:40 UTC, Str1kez commented on clocks/meetings/views.py
> +    lookup_field = "id"
так pk у тебя и есть id

2024-09-17 08:47 UTC, Str1kez commented on clocks/rooms/views.py
> +        return Room.objects.get(id=self.kwargs.get("id"))
ну да, в url передаешь и логика подефолту так работает, если `queryset` указан. Если не хочешь через `queryset`, то хотя бы `get_object_or_404` используй

2024-09-21 15:23 UTC, Str1kez commented on Dockerfile
> +RUN python manage.py collectstatic --noinput
мало того, что не убрал, так еще и тут добавил  😂

2024-09-21 15:28 UTC, Str1kez commented on clocks/meetings/serializers.py
> +        fields = ["id", "room", "task_name", "votes", "average_score", "active"]
```suggestion
        fields = '__all__'
```

2024-09-21 15:41 UTC, Str1kez commented on clocks/meetings/serializers.py
> +                self.fields.pop(field_name)
а там дикт в кэше, все ок тогда

2024-09-21 15:45 UTC, Str1kez commented on clocks/meetings/views.py
> +    def get_serializer(self, *args, **kwargs):
зачем? там ведь по дефолту все поля

2024-09-21 15:51 UTC, Str1kez commented on clocks/meetings/views.py
> +    queryset = Meeting.objects.all()
```suggestion
    queryset = Meeting.objects.select_related('room').filter(active=True)
```

2024-09-21 15:51 UTC, Str1kez commented on clocks/meetings/views.py
> +    queryset = Meeting.objects.all()
не будет доп запроса для комнаты и сразу активный будет искаться

2024-09-21 15:56 UTC, Str1kez commented on clocks/meetings/views.py
> +    def update(self, request, *args, **kwargs):
нужно переопределять `perform_update` здесь весь функционал `UpdateAPIView` теряется

2024-09-21 15:57 UTC, Str1kez commented on clocks/meetings/views.py
> +    def update(self, request, *args, **kwargs):
аналогично не тот метод

2024-09-21 16:06 UTC, Str1kez commented on clocks/meetings/views.py
> +                                         response_status=status.HTTP_200_OK)
Подход неправильный, нужен отдельный сериалайзер для обновления митинга, тогда не надо будет костылить так вьюшки. И вообще надо разделять сериализаторы, один для чтения, другой для создания, другой для обновления. А то ты один сериализатор мучаешь с динамическими `fields`

2024-09-21 16:08 UTC, Str1kez commented on clocks/meetings/views.py
> +        meeting.save()
это не `POST` запрос, не должно быть тут изменения модели

2024-09-21 16:14 UTC, Str1kez commented on clocks/rooms/models.py
> +    current_meeting = models.OneToOneField(
тогда оставь тут, а в meeting удали FK и поправь везде код

2024-09-21 16:16 UTC, Str1kez commented on clocks/rooms/serializers.py
> +        fields = ["id", "name", "is_active", "users", "current_meeting_id"]
```suggestion
        fields = '__all__'
```

2024-09-21 16:16 UTC, Str1kez commented on clocks/meetings/serializers.py
> +        fields = ["id", "room", "task_name", "votes", "average_score", "active"]
```suggestion
        fields = '__all__'
```

2024-09-21 16:20 UTC, Str1kez commented on clocks/rooms/views.py
> +                "role": "observer" if role == "observer" else "voter",
UPD: Аналогично, напиши сериалайзер для получения данных о комнате, которых будет возвращать такой dict

2024-09-21 16:24 UTC, Str1kez commented on clocks/rooms/views.py
> +        return Meeting.objects.filter(room_id=self.kwargs.get("pk"))
Тоже не нужно, задай 
```
queryset = Meeting.objects.all()
lookup_field = 'room_id'
```
сюда же можешь добавить пагинатор

2024-09-21 16:27 UTC, Str1kez commented on clocks/meetings/views.py
> +                                         response_status=status.HTTP_200_OK)
RoomSerializer в эту же тему

2024-09-22 10:09 UTC, PhonikTop commented on Dockerfile
> +RUN python manage.py collectstatic --noinput
> мало того, что не убрал, так еще и тут добавил 😂

а куда их деть тогда🤕

2024-09-22 10:19 UTC, PhonikTop commented on clocks/meetings/views.py
> +        meeting.save()
> это не `POST` запрос, не должно быть тут изменения модели

а если поменяю на UpdateAPIView?

2024-09-22 11:35 UTC, PhonikTop commented on clocks/rooms/views.py
> +        return Meeting.objects.filter(room_id=self.kwargs.get("pk"))
А как он будет фильтровать queryset по нужной комнате?

2024-09-24 18:27 UTC, PhonikTop commented on clocks/rooms/views.py
> +        return Room.objects.get(id=self.kwargs.get("id"))
Так через get_object_or_404 выдает только один объект, а мне нужно несколько. А если через queryset, то он не фильтрует по значению из lookup_fields и выдает просто все активные комнаты.

2024-10-17 16:04 UTC, Str1kez reviewed
оказывается вот как это работает, лоол

2024-10-17 16:04 UTC, Str1kez commented on requirements.txt
> +asgiref~=3.8.1
так же как с джангой, укажи везде точные версии. Некоторые пакеты вообще без версий

2024-10-17 16:04 UTC, Str1kez commented on Dockerfile
> +RUN python manage.py collectstatic --noinput
отдельный скрипт в папку `bin/migrations.sh`

2024-10-17 16:04 UTC, Str1kez commented on clocks/meetings/models.py
> +        self.save()
тогда это все уж в logic

2024-10-17 16:04 UTC, Str1kez commented on clocks/meetings/models.py
> +        self.save()
и импорт каждый раз = плохо

2024-10-17 16:04 UTC, Str1kez commented on clocks/meetings/models.py
> +        return f"Meeting for {self.room.name} - {self.task_name}"
зачем дергать второй раз ради получения строки? Поменяй на self.room_id

2024-10-17 16:04 UTC, Str1kez commented on clocks/meetings/models.py
> +        self.save()
и почему get_, ты тут ничего не возвращаешь

2024-10-17 16:04 UTC, Str1kez commented on clocks/users/views.py
> +        room = get_object_or_404(Room, id=self.request.data.get("room_id"))
слишком много лишних запросов в бд в этом методе, и почему проверка существования комнаты почти в конце? Если ее нет, зачем все выше обрабатывать? И наверное лучше комнату как path параметр в url

2024-10-17 16:04 UTC, Str1kez commented on clocks/meetings/views.py
> +        room.save()
комната же в сериализаторе достается + валидацию можно в нем же сделать

2024-10-17 16:04 UTC, Str1kez commented on clocks/meetings/views.py
> +
не будет такого по кверисету

2024-10-17 16:04 UTC, Str1kez commented on clocks/rooms/views.py
> +        return get_list_or_404(Meeting, room_id=self.kwargs.get("pk"))
почему не просто через кверисет в классе?

2024-10-17 16:04 UTC, Str1kez commented on clocks/settings/settings.py
странности какие-то

2024-10-17 16:04 UTC, Str1kez commented on clocks/rooms/views.py
> +        return Meeting.objects.filter(room_id=self.kwargs.get("pk"))
он же в методе get_object по lookup_field вызывает get_or_404

2024-10-17 16:04 UTC, Str1kez commented on clocks/users/redis_client.py
> +class RedisClient:
А это зачем все? Почему не использовать кэш джанги через редис?

2024-10-17 16:04 UTC, Str1kez commented on clocks/users/views.py
> +        token = cookie_utils.cookie_decrypt(str(self.request.COOKIES.get("user")))
~exceptions не обрабатываешь~, оказывается ты внутри обрабатываешь, хотя мог сюда свои Exception от данного сервиса прокидывать, чтобы явно понимать, что шифрование пошло не так

2024-10-17 16:04 UTC, Str1kez commented on clocks/api/api_utils.py
> +class Cookies_utils:
а в чем смысл класса? Можно отдельными функциями, а Fernet в глобальную

2024-10-20 15:27 UTC, PhonikTop commented on clocks/settings/settings.py
> странности какие-то

почему?

2024-10-20 15:31 UTC, PhonikTop commented on clocks/meetings/models.py
> +        self.save()
> тогда это все уж в logic

А почему?

2024-10-20 15:45 UTC, PhonikTop commented on clocks/users/views.py
> +        room = get_object_or_404(Room, id=self.request.data.get("room_id"))
> И наверное лучше комнату как path параметр в url

почему?

2024-10-22 21:43 UTC, PhonikTop commented on clocks/rooms/views.py
> +        return get_list_or_404(Meeting, room_id=self.kwargs.get("pk"))
Я не нашел, как это сделать для списка

2024-10-23 05:24 UTC, PhonikTop commented on clocks/meetings/models.py
> +        self.save()
> тогда это все уж в logic

Там же нету никакой логики, чтобы выносить её туда. Только изменение данных о конкретном голосовании и очистка списка пользователей связанной комнаты.

2024-10-24 10:20 UTC, PhonikTop commented on clocks/settings/settings.py
> странности какие-то
> 

Я пытался сделать абсолютные импорты. Серёга посоветовал добавить этот код в settings, но у меня ничего не вышло. В итоге он сказал, что можно оставить импорты в том виде, в каком они у меня уже есть. Я решил сохранить этот код на всякий случай – он не мешает работе, а если в будущем разберусь, как исправить ошибку с абсолютными импортами, мне не придётся заново это писать.

2024-10-27 18:53 UTC, Str1kez commented on clocks/meetings/models.py
> +        self.save()
все что ты написал и есть бизнес логика)) А тут получается модель использует бизнес логику, чего быть не должно

2024-10-27 19:05 UTC, Str1kez commented on clocks/meetings/views.py
> +        meeting.end_meeting()
1. Как будто тут и не нужен сериализатор, а хватит `lookup_field`
2. В `perform_update` другие аргументы прилетают, а у тебя сигнатура `update`

2024-10-27 19:06 UTC, Str1kez commented on clocks/meetings/views.py
> +        meeting.end_meeting()
в `RestartMeetingView` аналогично

2024-10-27 19:14 UTC, Str1kez commented on clocks/meetings/views.py
> +        meeting.save()
1. В этот сериализатор как будто можно в запросе передать `average_score`, а это поле не должно ли быть `read-only`?
2. И как будто `perform_update` работает после инициализации сериализатора и в результат не попадет нововычисленный `average_score`
3. Это так же сигнатура `update`, так как в `perform_update` передается только сериализатор

2024-10-27 19:17 UTC, Str1kez commented on clocks/rooms/views.py
> +        return get_list_or_404(Meeting, room_id=self.kwargs.get("pk"))
Ты не нашел как сделать так, чтобы при пустом списке отдавало 404? Если да, то оно тебе надо?) Можно отдавать 200 с пустым списком, это ок, ведь ты запрашиваешь коллекцию объектов, а не единичный

2024-10-27 19:22 UTC, Str1kez commented on clocks/rooms/views.py
> +        return get_list_or_404(Meeting, room_id=self.kwargs.get("pk"))
К тому же переопределять выдачу `queryset`, который можно разбить на страницы (чтобы выгружать меньше данных), на список всех сессий - не очень хорошо

2024-10-27 19:32 UTC, Str1kez commented on clocks/settings/settings.py
> +    f"postgres://{get_env_param_str('POSTGRES_USER')}:{get_env_param_str('POSTGRES_PASSWORD')}@watchy_db:5432/{get_env_param_str('POSTGRES_DB')}")
А почему не сразу закинуть в env переменную?
```env
DATABASE_URL=postgres://user:password@watchy_db:5432/clocks
```

2024-10-27 19:35 UTC, Str1kez commented on clocks/users/redis_client.py
> +def save_new_client_to_cache(token, nickname: str, role: str, ttl: int = 432000) -> None:
```suggestion

DEFAULT_TOKEN_TTL = 60 * 60 * 24 * 5  # 5 days

def save_new_client_to_cache(token, nickname: str, role: str, ttl: int = DEFAULT_TOKEN_TTL) -> None:
```

так гораздо понятнее будет

2024-10-27 19:36 UTC, Str1kez commented on clocks/users/redis_client.py
> +    return cache.get(token) is not None
можно проще без взятия объекта
```suggestion
    return bool(cache.ttl(token))
```

2024-10-27 19:43 UTC, Str1kez commented on clocks/users/views.py
> +        room = get_object_or_404(Room, id=self.request.data.get("room_id"))
Потому что по сути это `UpdateApiView` для `Room`. Особенно первые строки метода это и есть получение объекта по кверисету и `id` по `lookup_field`

2024-10-27 19:53 UTC, Str1kez commented on clocks/users/views.py
> +            raise ValidationError({"error": "User exists"})
Проверка токена должна быть в самом начале, а то много логики уже сделал, а проверил только тут

2024-10-27 19:54 UTC, Str1kez commented on clocks/users/views.py
> +        token = cookie_decrypt(str(self.request.COOKIES.get("user")))
сначала лучше проверь, что кука вообще есть, а потом возможный токен можно отправить на расшифровку

2024-10-27 19:55 UTC, Str1kez commented on clocks/users/views.py
> +        token = cookie_decrypt(str(self.request.COOKIES.get("user")))
Потому что дешифровать `'None'` - лишняя работа

2024-10-27 19:58 UTC, Str1kez commented on clocks/users/views.py
> +        if not all(user_data.values()):
```suggestion
        if not user_data:
```

2024-10-27 20:02 UTC, Str1kez commented on clocks/ws/consumers.py
> +                response = await getattr(self, action)(text_data_json)
`action` не тот, то надо обработать исключение

2024-10-27 20:04 UTC, Str1kez commented on clocks/ws/consumers.py
> +        return await database_sync_to_async(get_object_or_404)(model, **filters)
```suggestion
        return await aget_object_or_404(model, **filters)
```

2024-10-27 20:12 UTC, Str1kez commented on clocks/ws/consumers.py
> +        )()
```suggestion
        exists = await Meeting.objects.filter(room_id=scope, active=True).aexists()
```

2024-10-27 20:15 UTC, Str1kez commented on clocks/ws/consumers.py
Кстати, не рассматривал этот пакет? Он как будто сильно упростил бы жизнь

https://github.com/NilCoalescing/djangochannelsrestframework

2024-10-27 20:24 UTC, Str1kez commented on docker-compose.prod.yml
> +      - static:/Clocks/static
а зачем две статики? Вроде на nginx хватает

2024-10-27 20:29 UTC, Str1kez commented on nginx/prod.conf
вот это вряд ли так будет... и статики нет

2024-11-02 23:53 UTC, PhonikTop commented on clocks/users/views.py
> +            raise ValidationError({"error": "User exists"})
> Проверка токена должна быть в самом начале, а то много логики уже сделал, а проверил только тут

Так все сверху - тоже часть проверки

2024-11-03 00:16 UTC, PhonikTop commented on clocks/settings/settings.py
> +    f"postgres://{get_env_param_str('POSTGRES_USER')}:{get_env_param_str('POSTGRES_PASSWORD')}@watchy_db:5432/{get_env_param_str('POSTGRES_DB')}")
> А почему не сразу закинуть в env переменную?
> 
> ```dotenv
> DATABASE_URL=postgres://user:password@watchy_db:5432/clocks
> ```

Эти переменные используются еще и для бд. 
Это удобно тем, что не нужно переписывать эти переменные вручную для апи из бд. Для смены пароля/логина, нужно просто изменить одну переменную в .env файле, а не переписывать дополнительно еще другую переменные в docker-compose.yml

2024-11-03 11:51 UTC, PhonikTop commented on clocks/meetings/views.py
> +        meeting.save()
> 1. В этот сериализатор как будто можно в запросе передать `average_score`, а это поле не должно ли быть `read-only`?

Немного не понял.

2024-11-03 21:07 UTC, PhonikTop commented on clocks/ws/consumers.py
> Кстати, не рассматривал этот пакет? Он как будто сильно упростил бы жизнь
> 
> https://github.com/NilCoalescing/djangochannelsrestframework

Выглядит интересно, но как-то сомнительно. Не будет ли с ней еще больше проблем, и сможет ли кто-то другой разобраться в моем коде.🤷🏻‍♂️

2024-11-03 21:24 UTC, PhonikTop commented on clocks/rooms/views.py
> +        return get_list_or_404(Meeting, room_id=self.kwargs.get("pk"))
> Ты не нашел как сделать так, чтобы при пустом списке отдавало 404?


Нееее. Если вкратце, я дурак почему-то решил, что у меня с queryset, выдаются даже те голосования, которые не привязаны к конкретно запрашиваемой комнате.
Щас заново проверил с queryset все работает, как надо.

2024-11-04 18:47 UTC, Str1kez commented on clocks/rooms/views.py
> +        return get_list_or_404(Meeting, room_id=self.kwargs.get("pk"))
не может быть такого, если ты правильно указал queryset
```
queryset = Meeting.objects.all()
lookup_field = 'room_id'
```

2024-11-04 18:52 UTC, Str1kez commented on clocks/users/views.py
> +            raise ValidationError({"error": "User exists"})
Нет, ты просто все здесь запутал) У тебя токена зависит только от куки, но лишнюю работу по проверке данных ты уже сделал, хотя куку проверять можно и в начале

2024-11-04 19:01 UTC, Str1kez commented on clocks/users/views.py
> +        token = cookie_decrypt(cookie) if cookie else str(uuid.uuid4())
лучше рейзить исключение, иначе сохранишь token = None

2024-11-04 19:04 UTC, Str1kez commented on clocks/users/views.py
> +            raise ValidationError("User cookie is not valid")
это вообще не относится к логике получения объекта, надо вынести выше на слой проверки аутентификации

2024-11-04 19:06 UTC, Str1kez commented
И еще вопрос по моделям, почему бы не добавить created, updated?

2024-11-09 18:32 UTC, PhonikTop commented
> И еще вопрос по моделям, почему бы не добавить created, updated?

А для чего они?

2024-11-16 18:58 UTC, Str1kez commented
> > И еще вопрос по моделям, почему бы не добавить created, updated?
> 
> А для чего они?

чтобы видеть, когда была создана комната, таска

2024-11-16 18:59 UTC, Str1kez commented on clocks/ws/consumers.py
он вроде как раз делает работу с вебсокетом похожей на обычные generic views

2024-11-16 19:01 UTC, Str1kez commented on clocks/settings/settings.py
> +    f"postgres://{get_env_param_str('POSTGRES_USER')}:{get_env_param_str('POSTGRES_PASSWORD')}@watchy_db:5432/{get_env_param_str('POSTGRES_DB')}")
а кому надо будет менять пароль и юзера для локальной бд? 😂

2024-11-16 19:22 UTC, Str1kez commented on clocks/meetings/views.py
> +        meeting.save()
Да, там кусок кода другой, но все то же. В ручку можно передать average_score, ведь сериализатор это позволяет. Второй пункт тоже остается нерабочим

2024-12-20 18:35 UTC, PhonikTop commented on clocks/ws/consumers.py
> Кстати, не рассматривал этот пакет? Он как будто сильно упростил бы жизнь
> 
> https://github.com/NilCoalescing/djangochannelsrestframework

Я попробовал ее использовать, но она не предназначена для работы с группами и методов. В ней нету методов для отправки сообщений в группу или для создания/удаления самой группы.

2025-01-05 18:49 UTC, Str1kez commented on docker-compose.yml
> +    image: postgres:14-alpine
17 уже вышел)

2025-01-05 19:08 UTC, Str1kez commented on Makefile
> +restart: stop start
`docker-compose restart` не подходит?

2025-01-05 20:40 UTC, Str1kez requested changes

2025-01-05 20:40 UTC, Str1kez commented on Makefile
> +restart: stop start
`docker-compose restart` не подходит?

2025-01-05 20:40 UTC, Str1kez commented on Makefile
> +	@find . -name \*.pyc -delete
откуда они появляются?

2025-01-05 20:40 UTC, Str1kez commented on Makefile
> +ifndef NO_DB_RESET
двойное отрицание плохо смотрится `ifdef DB_RESET` лучше наверное

2025-01-05 20:40 UTC, Str1kez commented on Makefile
> +	@docker-compose run --rm watchy-api bash
Странно, для чего это? Что мешает зайти в рабочий контейнер через `docker-compose exec -ti`?

2025-01-05 20:40 UTC, Str1kez commented on Makefile
> +	@docker-compose logs -f
Зачем они вообще нужны тебе были?) Вроде ничего сложного написать `docker-compose <action>`

2025-01-05 20:40 UTC, Str1kez commented on clocks/rooms/redis_client.py
> +    def get_user(self, user_uuid: str) -> Optional[Dict[str, Optional[str]]]:
```suggestion
    def get_user(self, user_uuid: str) -> dict[str, str | None] | None
```

2025-01-05 20:40 UTC, Str1kez commented on clocks/rooms/redis_client.py
> +    def get_user(self, user_uuid: str) -> Optional[Dict[str, Optional[str]]]:
Уже давно не надо использовать `Optional`

2025-01-05 20:40 UTC, Str1kez commented on clocks/rooms/redis_client.py
> +        cache.set(user_key, {"role": role, "nickname": nickname, "vote": vote}, timeout=self.ttl)
лучше в явную структуру (dataclass, namedtuple). Данные же в одном виде всегда

2025-01-05 20:40 UTC, Str1kez commented on clocks/rooms/redis_client.py
> +        user_key = f"user:{uuid}:data"
в нескольких методах этот ключ создаешь, в одном месте поменяешь – везде искать будешь?

2025-01-05 20:40 UTC, Str1kez commented on clocks/users/serializers.py
> +    role = serializers.ChoiceField(choices=[("observer", "observer"), ("voter", "voter")])
вынеси в отдельный класс чойсов `UserRoleChoices(TextChoices):`, раз есть определенный набор ролей. Этот класс можно использовать в других методах

2025-01-05 20:40 UTC, Str1kez commented on clocks/rooms/redis_client.py
> +    def add_user(self, uuid: str, role: str, nickname: str, vote: Optional[str] = None) -> None:
```suggestion
    def add_user(self, uuid: str, role: UserRoleChoices, nickname: str, vote: str | None = None) -> None:
```

2025-01-05 20:40 UTC, Str1kez commented on clocks/rooms/redis_client.py
> +    def get_votes_dict(self) -> Dict[str, str]:
Какой-то бесполезный метод
- Полностью включает твой метод выше (и почему-то его даже не использует)
- Название очень плохое

2025-01-05 20:40 UTC, Str1kez commented on clocks/rooms/redis_client.py
> +    def remove_user(self, user_uuid: str) -> None:
Транзакция не нужна? Один удалится, а в списке останется...

2025-01-05 20:40 UTC, Str1kez commented on clocks/rooms/redis_client.py
> +class RoomCacheManager:
Общие проблемы:
- Нет атомарности операций (иногда в методах она необходима)
- Использование устаревшей типизации (Dict, Optional, etc)
- Докстринги – лишнее, чтобы было понятнее лучше использовать [type aliases](https://docs.python.org/3/library/typing.html#type-aliases)
- Это уже не слой работы с данными, а скорее сервис, надо назвать подходяще и в другой модуль закинуть

2025-01-05 20:40 UTC, Str1kez commented on clocks/ws/consumers.py
вообще-то есть, ну ок)

2025-01-05 20:40 UTC, Str1kez commented on clocks/ws/actions.py
> +        return Meeting.objects.filter(room=self.consumer.lookup_id, active=True).select_related()
передать в `select_related` забыл? И `async` не нужен

2025-01-05 20:40 UTC, Str1kez commented on clocks/users/views.py
> +    queryset = Room.objects.all()
наверное только активные нужны

2025-01-05 20:40 UTC, Str1kez commented on clocks/users/serializers.py
> +            raise ValidationError({"error": "Room instance is required in context"})
тебе в контекст всегда будет приходить, или 404 отдаваться

2025-01-05 20:40 UTC, Str1kez commented on clocks/users/serializers.py
> +        if not current_meeting:
```suggestion
        if not Meeting.objects.filter(room_id=room.id, active=True).exists():
```

2025-01-05 20:40 UTC, Str1kez commented on clocks/rooms/views.py
> +        return get_list_or_404(Meeting, room_id=self.kwargs.get("pk"))
С этим как дела обстоят?

2025-01-05 20:40 UTC, Str1kez commented on clocks/rooms/redis_client.py
> +        if self.get_user(uuid):
Лишний метод, он должен проверять просто наличие в кэше

2025-01-05 20:40 UTC, Str1kez commented on clocks/rooms/views.py
> +        participants = room_cache.get_room_users()
А почему решил вынести участников в кэш, а не хранить как раньше?

2025-01-05 20:40 UTC, Str1kez commented on clocks/ws/actions.py
> +            lambda: (room_cache.get_users_by_role("voter"), room_cache.get_votes())
почему нормально не разбить на две строки с вызовами `sync_to_async`?

2025-01-27 18:15 UTC, PhonikTop commented on clocks/rooms/views.py
> +        participants = room_cache.get_room_users()
Подумал, что так будет удобнее и структура будет лучше.

2025-01-27 18:59 UTC, PhonikTop commented on Makefile
> +restart: stop start
тогда будет бд сбрасывать

2025-01-27 19:38 UTC, PhonikTop commented on Makefile
> +	@docker-compose run --rm watchy-api bash
А это не праивльно? Мне просто так удобнее, меньше печатать.

2025-01-27 19:38 UTC, PhonikTop commented on Makefile
> +	@docker-compose logs -f
Ну меньше печатать просто)

2025-07-14 14:57 UTC, merged